### ISSUE TITLE
Problem sliding right the drawer 

### ISSUE THREAD

**Issue by Dannyboy2609** [amarmesic/windows-phone-navigation-drawer#1]
As the title say, if you slide the open drawer to the right, it will jump to some crazy animation and close the drawer, can you test this behavior ?

**Comment by priombiswas89** [comment]
I have tested and it's working perfectly.

```
 On Tuesday, December 9, 2014 9:35 AM, Dannyboy2609 <notifications@github.com> wrote:
```

 As the title say, if you slide the open drawer to the right, it will jump to some crazy animation and close the drawer, can you test this behavior ?—

**Comment by Dannyboy2609** [comment]
![captures](https://cloud.githubusercontent.com/assets/6822423/5356719/0e6db154-7fd2-11e4-980c-2abee9391fa7.png)

Steps to recreate the behavior:
- Open the drawer 
- Touch the right part of the opened drawer (not the shadow)
- Drag to the right and release touch

This behavior happens and the console show "A first chance exception of type 'System.OverflowException' occurred in mscorlib.ni.dll"

This is the zipped project that I downloaded from here

**Comment by amarmesic** [comment]
@Dannyboy2609 thanks for the feedback... will look into this asap

**Comment by minglini** [comment]
Any updates on this problem?

**Comment by leojplin** [comment]
Yes, we do need a solution to this ASAP. We can't put out a buggy control to the WP community!

**Comment by XHotSniperX** [comment]
I agree. It would be nice when this software gets more updates because it is really cool.

**Comment by amarmesic** [comment]
Sorry guys for the slow response... I've updated the lib and fixed this issue. Test it if you get the chance.
