### ISSUE TITLE
Windows 10 support

### ISSUE THREAD

**Issue by rafakwolf** [amarmesic/windows-phone-navigation-drawer#10]
Awesome lib, but needs windows 10 support

**Comment by konradbartecki** [comment]
Windows 10 UWP supports navigation drawer / hamburger menu natively. It will be a lot more reasonable to use native SplitView than some custom implementation.
Check it out: http://blogs.msdn.com/b/quick_thoughts/archive/2015/06/01/windows-10-build-your-first-hamburger-menu.aspx

**Comment by amarmesic** [comment]
Agreed with @konradbartecki. 

@rafakwolf Thanks for the feedback.
