### ISSUE TITLE
DataBinding IsDrawerOpen fails + patch 

### ISSUE THREAD

**Issue by TsengSR** [amarmesic/windows-phone-navigation-drawer#2]
In order to access the current IsDrawerOpen state, I had to Databind it into my ViewModel. 

But the IsDrawerOpen was implemented as a normal Property, thus TwoWay Databinding failed with an exception.

To allow TwoWay DataBinding in XAML it is required to implement an Dependency Property. I have added it. 

I am not very familiar with git pull requests, so I just created a patch file (it's a very small change anyways) 

The Patch file can be found https://gist.github.com/TsengSR/6581d1ccc6eed5de3579

Then I can DataBind my property to my ViewModel and my ViewModel is always aware then the drawer state changes

```
IsDrawerOpen="{Binding Mode=TwoWay, Path=IsOpen, UpdateSourceTrigger=PropertyChanged}"
```

I needed this to make it work with Prism, as Prism has it's own Navigation Manager and was closing my Page which contained the navigation, when the drawer was opened, which was very undesired.

**Comment by amarmesic** [comment]
Thank you @TsengSR 

Patch applied.
