### ISSUE TITLE
Menu icon doesn't open drawer in a specific case

### ISSUE THREAD

**Issue by XHotSniperX** [amarmesic/windows-phone-navigation-drawer#4]
First of all this is a very cool library. Thank you very much!

I found an issue:
If you tap on the main panel to close the drawer and then tap on the menu icon to open it again it will not work. You have to tap the menu icon twice in this case to make it work.

**Comment by amarmesic** [comment]
Thanks for the feedback @XHotSniperX 

Found the problem... will push changes asap

**Comment by XHotSniperX** [comment]
Thank you!!! :)
